import { Inter } from 'next/font/google'
import './global.scss'
import Header from './components/Header'
import Footer from './components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Home',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				<main className='main'>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
