import { Inika } from 'next/font/google';
import { Header, Footer } from '../layout';
import '../assets/styles/global.scss';
import './global.css';
import { Metadata } from 'next';
import { ReactNode } from 'react';

const inter = Inika({ subsets: ['latin'], weight: '700' });

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

interface IProps {
  children: ReactNode;
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="main">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
